n= int(input('Digite um número:'))
print('{}x1 ={}'.format(n,n*1))
print('{}x2 ={}'.format(n,n*2))
print('{}x3 ={}'.format(n,n*3))
print('{}x4 ={}'.format(n,n*4))
print('{}x5 ={}'.format(n,n*5))
print('{}x6 ={}'.format(n,n*6))
print('{}x7 ={}'.format(n,n*7))